EducationPlatform/Controllers/ProfileController.cs
using System.Linq;
using System.Threading.Tasks;
using EducationPlatform.Models.Entities;
using EducationPlatform.Models.ViewModels.Students;
using EducationPlatform.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EducationPlatform.Controllers
{
    [Authorize(Roles = "Admin, Teacher, Student")]
    public class ProfileController : Controller
    {
        private readonly IStudentsService _studentService;
        private readonly IUsersService _usersService;
        private readonly UserManager<User> _userManager;
        private readonly IBotService _botService;
        private readonly ICoursesService _coursesService;

        public ProfileController
        (
            IUsersService usersService,
            IStudentsService studentService,
            UserManager<User> userManager,
            IBotService botService,
            ICoursesService coursesService
        )
        {
            _usersService = usersService;
            _studentService = studentService;
            _userManager = userManager;
            _botService = botService;
            _coursesService = coursesService;
        }

        public async Task<IActionResult> Index(bool isModalWindowShowRequired = false, string error = null, string message = null)
        {
            string id = _userManager.GetUserId(User);

            ViewBag.HasTwoFactor = await _usersService.GetTwoFactorUserByIdAsync(id) != null;
            ViewBag.BotAuthorizationKey = await _botService.GetAuthorizationKey(id);
            ViewBag.IsModalWindowShowRequired = isModalWindowShowRequired;

            if (error != null || message != null)
            {
                ViewBag.Error = error;
                ViewBag.Message = message;
            }

            if (User.IsInRole("Teacher"))
            {
                ViewBag.Courses = (await _coursesService.GetTeacherCoursesAsync(id)).Count();
            }

            if (User.IsInRole("Student"))
            {
                StudentViewModel user = await _studentService.GetByUserIdAsync(id);
                return View("Student", user);
            }
            else
            {
                User user = await _userManager.FindByIdAsync(id);

                if (User.IsInRole("Teacher"))
                {
                    return View("Teacher", user);
                }
                else
                {
                    return View("Admin", user);
                }
            }
        }

        public async Task<IActionResult> GeneradeBotKey(string id)
        {
            if(await _botService.GetAuthorizationKey(id) == null)
            {
                await _botService.CreateAuthorizationKey(id);
            }

            return RedirectToAction("Index", new { isModalWindowShowRequired = true });
        }
    }
}

EducationPlatform/Controllers/ScheduleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EducationPlatform.Models.ViewModels.Courses;
using EducationPlatform.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EducationPlatform.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly IScheduleService _scheduleService;
        private readonly ICoursesService _coursesService;

        public ScheduleController(IScheduleService scheduleService, ICoursesService coursesService)
        {
            _scheduleService = scheduleService;
            _coursesService = coursesService;
        }

        [Authorize(Roles = "Admin, Student, Teacher")]
        public async Task<IActionResult> Index()
        {
            CoursesIndexViewModel coursesIndexViewModel = new CoursesIndexViewModel()
            {
                Courses = (await _coursesService.GetCoursesAsync()).ToList()
            };
            return View(coursesIndexViewModel);
        }

        [Authorize(Roles = "Admin, Student, Teacher")]
        [Route("{controller}/{action}")]
        public async Task<IActionResult> GetAllCoursesSchedule()
        {
            var schedule = await _scheduleService.GetScheduleByAllCourses();
            if (schedule != null)
            {
                return Json(schedule);
            }
            return Json(new List<object>());
        }


        [Authorize(Roles = "Student")]
        [Route("{controller}/{action}/{id}")]
        public async Task<IActionResult> GetScheduleForStudent(string Id)
        {
            var schedule = await _scheduleService.GetScheduleByStudent(Id);
            if (schedule != null)
            {
                return Json(schedule);
            }
            return Json(new List<object>());

        }

        [Authorize(Roles = "Teacher")]
        [Route("{controller}/{action}/{email}")]
        public async Task<IActionResult> GetTeacherSchedule(string email)
        {
            var schedule = await _scheduleService.GetScheduleByTeacher(email);
            if (schedule != null)
            {
                return Json(schedule);
            }
            return Json(new List<object>());
        }


        [Authorize(Roles = "Admin")]
        [Route("{controller}/{action}")]
        public async Task<IActionResult> GetCoursesScheduleByFilter(List<int> coursesId)
        {
            var coursesSchedule = await _scheduleService.GetCoursesSchedulebyFilter(coursesId);
            if (coursesSchedule != null)
            {
                return Json(coursesSchedule);
            }
            return Json(new List<object>());
        }


        [Authorize(Roles = "Admin")]
        [Route("{controller}/{action}")]
        public async Task<IActionResult> GetCoursesScheduleByTeacheFilter(List<string> emails)
        {
            var coursesSchedule = await _scheduleService.GetCoursesScheduleByTeacherFilter(emails);
            if (coursesSchedule != null)
            {
                return Json(coursesSchedule);
            }
            return Json(new List<object>());
        }
    }
}

EducationPlatform/Views/Shared/_ChangeEmailModal.cshtml
@model EducationPlatform.Models.ViewModels.Account.ChangeEmailViewModel
<div class="modal" id="emailModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Зміна Email</h4>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <form method="post" asp-controller="Account" asp-action="SubmitEmail" id="changeEmail">
                @Html.HiddenFor(x => x.Id, new { id = "user_id" })
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" asp-for="Email" placeholder="Введіть нову пошту" type="email" id="inputEmail" value="" required />
                        <span asp-validation-for="Email"></span>
                    </div>

                </div>
                <div class="modal-footer">
                    <button class="btn btn-light mr-auto" data-dismiss="modal">Відмінити</button>
                    <button type="submit" class="btn btn-primary" id="vasya">Змінити</button>
                </div>
            </form>
        </div>
    </div>
</div>

EducationPlatform/Views/Shared/_ChatBotPartial.cshtml
<button type="button" class="btn btn-primary h-100 d-flex text-center ml-2" data-toggle="modal" data-target="#chatBotModalWindow">
    Чат-бот
</button>

<div class="modal fade" id="chatBotModalWindow" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Чат-бот</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (ViewBag.BotAuthorizationKey == null)
                {
                    <span>Щоб почати користуватися чат-ботом згенеруйте собі ключ авторизації.</span>
                }
                else
                {
                    <span>Ваш код авторизації: <b>@ViewBag.BotAuthorizationKey.AuthorizationKey</b></span>
                }
            </div>
            <div class="modal-footer">
                @if (ViewBag.BotAuthorizationKey == null)
                {
                    <button type="submit" class="btn btn-primary">Згенерувати код</button>
                }
            </div>
        </div>
    </div>
</div>

@if(ViewBag.IsModalWindowShowRequired != null)
{
    @if(ViewBag.IsModalWindowShowRequired)
    {
        <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="~/js/modalWindow.js"></script>
    }
}

EducationPlatform/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<EducationPlatform.Models.Entities.User> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EducationPlatform</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/introjs.css" />
    <link rel="stylesheet" href="~/lib/template/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/lib/template/vendors/base/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/lib/template/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/template/css/style.css">
    <link rel="stylesheet" href="~/lib/template/css/theme-toggle.css" />
    @await RenderSectionAsync("Styles", false)
    <link rel="shortcut icon" href="~/lib/template/images/favicon-32x32.png" />
</head>
<body>

    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand brand-logo" href="/"><img id="logo" src="~/lib/template/images/Logo EP.svg" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="/"><img id="logoMini" src="~/lib/template/images/logo-mini-EP-black.svg" alt="logo" /></a>
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav mr-lg-4 w-100">
                    <li class="nav-item nav-search d-none d-lg-block w-100">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            <Gravatar email="@User.Identity.Name"></Gravatar>
                            <span class="nav-profile-name">@((await UserManager.GetUserAsync(User)).Email)</span>
                            @if (User.IsInRole("Student"))
                            {
                                <span class="role-label">(Студент)</span>
                            }
                            @if (User.IsInRole("Teacher"))
                            {
                                <span class="role-label">(Вчитель)</span>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <span class="role-label">(Адміністратор)</span>
                            }
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            <form method="get" asp-controller="@(User.IsInRole("Student") ? "Students" : "Teachers")" asp-action="Setting" asp-route-id="@UserManager.GetUserId(User)">
                                <button type="submit" class="dropdown-item">
                                    <i class="mdi mdi-settings text-primary"></i>
                                    Налаштування
                                </button>
                            </form>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="logout-btn"><i class="mdi mdi-logout text-primary"></i> Вихід</button>
                            </form>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Profile")">
                            <i class="mdi mdi-home menu-icon"></i>
                            <span class="menu-title">Профіль</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Schedule")" class="nav-link">
                            <i class="mdi mdi-book-multiple"></i>
                            <span class="ml-4 menu-title">Розклад</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Courses")" class="nav-link">
                            <i class="mdi mdi-file-document-box-outline menu-icon"></i>
                            <span class="menu-title">Курси</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Videos")" class="nav-link">
                            <i class="mdi mdi-video menu-icon"></i>
                            <span class="menu-title">Записи</span>
                        </a>
                    </li>
                    @if (User.IsInRole("Teacher") || User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Subjects")" class="nav-link">
                                <i class="mdi mdi-library-books"></i>
                                <span class="ml-4  menu-title">Предмети</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Teachers")" class="nav-link">
                                <i class="mdi mdi-account menu-icon"></i>
                                <span class="menu-title">Викладачі</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Students")" class="nav-link">
                                <i class="mdi mdi-account-multiple"></i>
                                <span class="ml-4 menu-title">Студенти</span>
                            </a>
                        </li>
                    }
                    <li class="nav-item">
                        <div class="theme-toggler">
                            <form method="post" asp-controller="Account" asp-action="InterfaceModeChange">
                                <label class="switch">
                                    <input id="theme-checkbox" type="checkbox">
                                    <span class="slider round"></span>
                                </label>
                            </form>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel ml-auto">
                <div class="content-wrapper">
                    <!-- - PUT YOUR CODE HERE - -->
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- End custom js for this page-->


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <!--jsdeliver-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- plugins:js -->
    <!-- Plugin js for this page-->
    <script src="~/lib/template/vendors/chart.js/Chart.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js"></script>
    <script src="~/lib/template/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/lib/template/js/off-canvas.js"></script>
    <script src="~/lib/template/js/hoverable-collapse.js"></script>
    <script src="~/lib/template/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/lib/template/js/dashboard.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/template/js/theme_toggle.js"></script>
    <script src="~/js/intro.js"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/js/intro.js"></script>
</body>
</html>

EducationPlatform/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Education Portal</title>
    <link rel="stylesheet" href="~/lib/template/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/lib/template/vendors/base/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/lib/template/css/style.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/introjs.css" />
    <link rel="shortcut icon" href="~/lib/template/images/favicon-32x32.png" />
    @RenderSection("Styles", false)
</head>

<body>
    <div class="container-scroller">
        <main class="container-fluid page-body-wrapper full-page-wrapper">
            @RenderBody()
        </main>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/lib/template/vendors/base/vendor.bundle.base.js"></script>
    <script src="~/lib/template/js/off-canvas.js"></script>
    <script src="~/lib/template/js/hoverable-collapse.js"></script>
    <script src="~/lib/template/js/template.js"></script>
    <script src="~/js/intro.js"></script>
    @RenderSection("Scripts", false)
</body>

</html>